### PR TITLE
Changed the server control thing (untested)

### PR DESCRIPTION
**Pull request by BanThoncc**
Can someone please test this

- [ ] Check this if you have tested this
- [ ] Check this if you have tested this and it worked

### CODE REVIEW

**Comment by ar06x** [comment]
Cant test till Friday (6 days)

**Comment by BanThoncc** [comment]
its friday can u test

**Comment by BanThoncc** [comment]
|h|
|-|
|h|

**Comment by BanThoncc** [comment]
> This have config

no

**Comment by mathmakgakpak** [comment]
ok you gave me working version THX!


closing

**Pull request closed without merging**
